export const AUDIT_CONSTANTS = {
  ACTIONS: [
    'USER_CREATED', 'USER_UPDATED', 'USER_DELETED',
    'MEMBERSHIP_APPLICATION_CREATED', 'MEMBERSHIP_STATUS_UPDATED',
    'LOAN_APPLICATION_CREATED', 'LOAN_STATUS_UPDATED',
    'CONTENT_CREATED', 'CONTENT_UPDATED', 'CONTENT_DELETED'
  ]
};
